/**
 * VeloCity Contracts — Agent Types
 *
 * Canonical type definitions for all 10 AI agents.
 * Reuses/extends the AgentName and AgentResponse types from src/types/index.ts.
 *
 * Agents: ALICE, MAX, QUINN, NOVA, REX, IVY, FINN, LENA, TESS, GABRIEL
 */

// ── Agent identity ─────────────────────────────────────────────────────────

/**
 * All agent names in the VeloCity platform.
 * Matches the registry in src/lib/agents/runAgent.ts and src/types/index.ts.
 */
export type AgentName =
  | "ALICE"   // Customer Intake & Classification
  | "MAX"     // Dispatch & Provider Matching
  | "QUINN"   // Quote & Pricing Guidance
  | "NOVA"    // Job Workflow Orchestration
  | "REX"     // Quality & Trust Monitoring
  | "IVY"     // Dispute Resolution
  | "FINN"    // Finance & Payment Monitoring
  | "LENA"    // Customer Retention & Rebooking
  | "TESS"    // Territory & Market Intelligence
  | "GABRIEL"; // Governance & Compliance

/**
 * Human-readable description of each agent's role.
 * Used for logging, dashboards, and audit trails.
 */
export const AGENT_ROLES: Record<AgentName, string> = {
  ALICE:   "Customer Intake & Classification",
  MAX:     "Dispatch & Provider Matching",
  QUINN:   "Quote & Pricing Guidance",
  NOVA:    "Job Workflow Orchestration",
  REX:     "Quality & Trust Monitoring",
  IVY:     "Dispute Resolution",
  FINN:    "Finance & Payment Monitoring",
  LENA:    "Customer Retention & Rebooking",
  TESS:    "Territory & Market Intelligence",
  GABRIEL: "Governance & Compliance",
} as const;

/** Type guard: check if a string is a valid AgentName */
export function isAgentName(value: string): value is AgentName {
  return Object.keys(AGENT_ROLES).includes(value);
}

// ── Agent context (passed into every agent run) ───────────────────────────

/**
 * Contextual metadata passed to every agent invocation.
 * Used for logging association and prompt enrichment.
 */
export interface AgentContext {
  /** Associated job ID, if applicable */
  jobId?: string;

  /** Associated user ID (customer, provider, or admin), if applicable */
  userId?: string;

  /** Tenant ID for multi-tenant isolation */
  tenantId?: string;

  /**
   * Optional trace ID for cross-hop observability.
   * When present, written to agent_logs for distributed tracing.
   */
  traceId?: string;
}

// ── Agent result ───────────────────────────────────────────────────────────

/**
 * Standard response envelope returned by every agent run.
 * Matches AgentResponse<T> in src/types/index.ts.
 *
 * @template T - Agent-specific output data type
 */
export interface AgentResult<T = Record<string, unknown>> {
  /** True if the agent produced a usable result (including fallback results) */
  success: boolean;

  /** Parsed agent output — null if the agent failed */
  data?: T;

  /** Error message if success is false */
  error?: string;

  /** Total tokens consumed by the Anthropic API call */
  tokensUsed?: number;

  /** Wall-clock latency in milliseconds */
  latencyMs?: number;

  /** True if the response came from a deterministic fallback (no AI call made) */
  isFallback?: boolean;
}

// ── Agent run record (persisted to agent_logs) ────────────────────────────

/**
 * The record shape written to the agent_logs table after every agent invocation.
 * Matches the agent_logs table schema.
 */
export interface AgentRunRecord {
  /** Auto-generated UUID */
  id?: string;

  /** Agent that handled this run */
  agent_name: AgentName;

  /** Tenant this run belongs to */
  tenant_id: string;

  /** Associated job, if applicable */
  job_id: string | null;

  /** Associated user, if applicable */
  user_id: string | null;

  /** Human-readable description of the action taken (agent.role) */
  action: string;

  /** The input message/context sent to the agent */
  input: Record<string, unknown>;

  /** The parsed agent output (AgentResult envelope) */
  output: Record<string, unknown>;

  /** Tokens consumed by the Anthropic API */
  tokens_used: number | null;

  /** Wall-clock latency in milliseconds */
  latency_ms: number | null;

  /** Error message, if the run failed */
  error: string | null;

  /**
   * Estimated cost in USD for this agent run.
   * Calculated from tokens_used × claude-sonnet-4 pricing.
   * Column to be added via migration (Wave 4).
   */
  cost_usd?: number | null;

  /**
   * Trace ID for cross-hop debugging (Wave 3+).
   * Propagated from the originating HTTP request.
   */
  trace_id?: string | null;

  /** ISO 8601 timestamp (auto-generated by DB) */
  created_at?: string;
}

// ── Agent capability registry (for documentation / runtime introspection) ─

/**
 * Describes an agent's capabilities and triggers.
 * Used for admin dashboards and documentation generation.
 */
export interface AgentCapability {
  /** Agent identifier */
  name: AgentName;

  /** Human-readable role */
  role: string;

  /**
   * Event types that trigger this agent via the router.
   * Not exhaustive — agents can also be called directly from handlers.
   */
  triggerEvents: string[];

  /** Whether this agent has a deterministic fallback when AI is unavailable */
  hasFallback: boolean;

  /** Anthropic model version used by this agent */
  model: string;
}
